# playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
  vars:
    os_auth_pw_max_age: 99999
    os_auth_pw_min_age: 0
    os_auth_pw_remember: 2
    os_auth_pam_passwdqc_enable: false
    