# playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
  vars:
    os_auth_pw_max_age: 99999
    os_auth_pw_min_age: 0
    os_auth_pw_remember: 2
    os_auth_pam_passwdqc_enable: false
    os_auth_retries: 0
  tasks:
    - name: Change root password
      user:
        name: root
        update_password: always
        password: $6$VOgiyM/DOroN$5riHRZQ6pGSK3VvXgdaqhtbC3IAmbUZNsVe9EAuW7WenbGyRX0E0CgHWpBHXK3Lvp3fTG7r0pTceDXw.YWTWv/
    