
variable "hcloud_token" {
  type    = string
  default = "FBovgSRwxr5NymiF6HQpC9D2SzADQFBNW2UHesyuSqd0g8BciEYUZbeQtr6kcumI"
}

source "hcloud" "autogenerated_1" {
  image        = "ubuntu-18.04"
  location     = "nbg1"
  server_type  = "cx11"
  ssh_username = "root"
  token        = "${var.hcloud_token}"
}

build {
  sources = ["source.hcloud.autogenerated_1"]

  provisioner "inspec" {
    extra_arguments = ["--no-distinct-exit"]
    profile         = "https://github.com/dev-sec/linux-baseline"
  }

}
