# Debian Config Playbook
- name: 'Configure FreeBSD Image'
  hosts: default
  become: true
  vars:
    ntp_timezone: Europe/Berlin
    ntp_server: 85.236.210.1
    dns_server_0: 85.236.210.1
    dns_server_1: 212.71.212.71

  tasks:

  - name: Upgrade all installed packages
    community.general.pkgng:
      name: "*"
      state: latest

  - name: Install NTP Chrony Package
    community.general.pkgng:
     name: chrony
     state: present
  
  # Copy NTP Client Config
  - name: Compile and copy chrony.conf
    template:
      src: ../chrony.conf.j2
      dest: /usr/local/etc/chrony.conf
  
  - name: Enable Chrony
    command: echo "chronyd_enable="YES"" >> /etc/rc.conf 

  - name: deploy resolv.conf template
    template:
      src: ../resolv.conf.j2
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644
