---

name: Packer FreeBSD 13

on:
  schedule:
    - cron: '0 12 */15 * *'
  push:
    paths:
      - 'FreeBSD/*'

jobs:
  packer:
    runs-on: ubuntu-latest
    name: freebsd-13

    steps:

      - name: Update Repos
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo add-apt-repository ppa:ansible/ansible

      - name: Install Utils
        run: sudo apt-get install -y qemu-system ansible packer

      - name: Download Ansible Collection
        run: ansible-galaxy collection install devsec.hardening community.general

      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: Validate Template
        run: |
          packer validate FreeBSD/FreeBSD-13.pkr.hcl

      # build artifact
      - name: Build Artifact
        env:
            PACKER_LOG: 1
        run: |
          packer build -color=false -on-error=abort FreeBSD/FreeBSD-13.pkr.hcl

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

      # additional steps to process artifacts
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.date.outputs.date }}
          files: |
            build/*.qcow2