---

name: Packer Ubuntu

on:
  push:
    paths:
      - '**Ubuntu**'

jobs:
  packer:
    runs-on: ubuntu-latest
    name: ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: Ubuntu/Ubuntu-20.04.pkr.hcl Ubuntu/Ubuntu-18.04.pkr.hcl

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: Ubuntu/Ubuntu-20.04.pkr.hcl Ubuntu/Ubuntu-18.04.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: Ubuntu/Ubuntu-20.04.pkr.hcl Ubuntu/Ubuntu-18.04.pkr.hcl
        env:
          PACKER_LOG: 1

      # additional steps to process artifacts
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          files: |
            *.qcow2